#!/usr/bin/python3
print("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Hello, World! - CGI Python</title>")
print("</head>")
print("<body>")
print("<h2>Hello, World! This is a CGI script written in Python.</h2>")
print("</body>")
print("</html>")